### ISSUE TITLE
Make Volunteer page work

### ISSUE THREAD

**Issue by nrhubbar** [rustbridge/rustbridge.io#2]
Currently the link in the header named volunteer does not do anything.

Create or move content to this page.

**Comment by nrhubbar** [comment]
https://i.imgur.com/LMFNqiI.png

**Comment by trentspi** [comment]
It looks like we don't have data for the volunteer page, so maybe this should just be a simple like Volunteer request form? Maybe with some information (data) about what volunteering may involve.  I think we will have to create content for this page...

**Comment by nrhubbar** [comment]
Perhaps we can talk to @ashleygwilliams about what sort of information belongs on this page.
